services:
  sentiment:
    build: ./sentiment_data_service
    ports:
      - "5001:5000"
    volumes:
      - ./sentiment_data_service/data:/app/data

  aggregator:
    build: ./process_data_service
    ports:
      - "5002:5000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - sentiment
      
  marketdata:
    build: ./market_data_service
    ports:
      - "5003:5000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - sentiment

  portfolio:
    build: ./portfolio_service
    ports:
      - "5004:5000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - aggregator
      - marketdata

  plot:
    build: ./plot_service
    ports:
      - "5005:5000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - portfolio