services:
  sentiment:
    build: ./sentiment_data_service
    container_name: sentiment_service
    ports:
      - "5001:5000"

  process:
    build: ./process_data_service
    container_name: process_service
    ports:
      - "5002:5000"
    depends_on:
      - sentiment
      
  marketdata:
    build: ./market_data_service
    container_name: marketdata_service
    ports:
      - "5003:5000"
    depends_on:
      - sentiment

  portfolio:
    build: ./portfolio_service
    container_name: portfolio_service
    ports:
      - "5004:5000"
    depends_on:
      - process
      - marketdata

  plot:
    build: ./plot_service
    container_name: plot_service
    ports:
      - "5005:5000"
    depends_on:
      - portfolio
  
  gateway:
    build: ./gateway
    container_name: gateway_service
    depends_on:
      - sentiment
      - process
      - marketdata
      - portfolio
      - plot
    ports:
      - "5000:5000"